apiVersion: apps/v1
kind: Deployment
metadata:
  name: uaa-deployment
spec:
  selector:
    matchLabels:
      app: uaa
  replicas: 1
  template:
    metadata:
      labels:
        app: uaa
    spec:
      containers:
        - name: uaa
          image: dtr.predix.io/pcs/uaa:75.18.0
          ports:
            - containerPort: 8080
          env:
          - name: CATALINA_OPTS
            value: '-Dspring.profiles.active=default'
          envFrom:
            - secretRef:
                name: uaa-jwt-grant-config
          volumeMounts:
            - name: uaa-yaml-config-volume
              mountPath: /uaa/uaa.yml
              subPath: uaa.yml
              readOnly: true
            - name: jwt-token-keys-volume
              mountPath: /uaa/secrets/jwt_token_keys.yml
              subPath: jwt_token_keys.yml
              readOnly: true
            - name: saml-keys-config-volume
              mountPath: /uaa/secrets/saml_keys_config.yml
              subPath: saml_keys_config.yml
              readOnly: true
      volumes:
        - name: uaa-yaml-config-volume
          configMap:
            name: uaa-yml-config
        - name: jwt-token-keys-volume
          secret:
            optional: false
            secretName: uaa-jwt-token-keys-secret
        - name: saml-keys-config-volume
          secret:
            optional: false
            secretName: uaa-saml-keys-secret
