apply(plugin: "java")
apply(plugin: "war")
apply(plugin: "org.springframework.boot")

war {
    archiveBaseName = "cloudfoundry-identity-statsd"
}

repositories {
    maven {
        credentials {
            username System.getenv('ARTIFACTORY_CREDENTIALS_USR')
            password System.getenv('ARTIFACTORY_CREDENTIALS_PSW')
        }
        url 'https://gart.software.gevernova.com/artifactory/pgog-fss-iam-uaa-mvn-virtual'
    }
}

dependencies {
    implementation(project(":cloudfoundry-identity-statsd-lib"))
    implementation(libraries.springBootStarterWeb){
        exclude(group: "org.glassfish", module: "jakarta.el")
    }
    providedCompile(libraries.tomcatEmbed)
    providedRuntime(libraries.springBootStarterTomcat){
        exclude(group: "org.glassfish", module: "jakarta.el")
    }
}

test {
    exclude("org/cloudfoundry/identity/statsd/integration/*.class")
    exclude("**/*IT.class")
}

integrationTest {}.onlyIf { //disable since we don't have any
    false
}

tasks.named('bootRun') {
    enabled = false
}
